### PR TITLE
Add Missing CTRL keys to wincrt unit

### PR DESCRIPTION
**Pull request by Zaaphod**
Add output for quite a number of missing CTRL Keys to the wincrt unit.

### CODE REVIEW

**Comment by chainq** [comment]
This is a read only mirror of the Free Pascal SVN repository. The FPC team do not accept pull requests and issue reports here. Please use the bugtracker at http://mantis.freepascal.org and submit a feature request with a patch.

**Comment by graemeg** [comment]
Thanks chainq. I've also posted a message in the FPC mailing list if somebody wanted to take a look (some FPC developers do use git - but not many). The best solution is to post patches to FPC's Mantis system.

**Comment by Zaaphod** [comment]
Sorry about posting in the wrong place.  I did not realize this was a read only mirror.  I cloned it a while ago and found it very helpful.    I will use the link above an attempt to get it posted correctly.

**Comment by Zaaphod** [comment]
I've posted to the bugtracker here:
http://mantis.freepascal.org/view.php?id=30599

**Pull request closed without merging**
